name: Build and Push Docker Image with firebase.json

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Create firebase.json file from GitHub Secret
    - name: Create firebase.json file from secret
      run: echo "${{ secrets.FIREBASE_JSON }}" > firebase.json

    # Step 5: Build Docker image with firebase.json included
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/procare_backend:latest .

    # Step 6: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/procare_backend:latest

    # cleanup: Remove firebase.json after the build
    - name: Clean up firebase.json
      run: rm -f firebase.json
